In [1]:
import numpy as np

In [2]:
t1a=np.zeros(72)
t1b=np.ones(76)
t1c=np.zeros(52)
t1=np.concatenate((t1a,t1b,t1c))


In [3]:
t2a=np.zeros(57)
t2b=np.ones(111)
t2c=np.zeros(32)
t2=np.concatenate((t2a,t2b,t2c))


In [4]:
t3a=np.zeros(90)
t3b=np.ones(110)
t3=np.concatenate((t3a,t3b))


In [5]:
t4a=np.zeros(30)
t4b=np.ones(132)
t4c=np.zeros(38)
t4=np.concatenate((t4a,t4b,t4c))

In [6]:
t5a=np.zeros(9)
t5b=np.ones(73)
t5c=np.zeros(21)
t5d=np.zeros(97)
t5=np.concatenate((t5a,t5b,t5c,t5d))

In [7]:
t6=np.ones(200)

In [8]:
t7a=np.ones(173)
t7b=np.zeros(27)
t7=np.concatenate((t7a,t7b))

In [9]:
t8a=np.ones(83)
t8b=np.zeros(117)
t8=np.concatenate((t8a,t8b))

In [10]:
t9a=np.ones(47)
t9b=np.zeros(153)
t9=np.concatenate((t9a,t9b))

In [11]:
t10a=np.ones(110)
t10b=np.zeros(90)
t10=np.concatenate((t10a,t10b))

In [12]:
t11a=np.zeros(122)
t11b=np.ones(40)
t11c=np.zeros(38)
t11=np.concatenate((t11a,t11b,t11c))

In [13]:
t12a=np.zeros(143)
t12b=np.ones(57)
t12=np.concatenate((t12a,t12b))

In [14]:
t13a=np.ones(144)
t13b=np.zeros(56)
t13=np.concatenate((t13a,t13b))
    

In [15]:
t14=np.ones(200)

In [16]:
t15a=np.zeros(139)
t15b=np.ones(61)
t15=np.concatenate((t15a,t15b))

In [17]:
t16a=np.zeros(129)
t16b=np.ones(71)
t16=np.concatenate((t16a,t16b))

In [18]:
t17a=np.zeros(55)
t17b=np.ones(65)
t17c=np.zeros(52)
t17d=np.ones(18)
t17e=np.zeros(10)
t17=np.concatenate((t17a,t17b,t17c,t17d,t17e))

In [19]:
t18a=np.zeros(54)
t18b=np.ones(84)
t18c=np.zeros(62)
t18=np.concatenate((t18a,t18b,t18c))

In [20]:
t19a=np.zeros(46)
t19b=np.ones(130)
t19c=np.zeros(24)
t19=np.concatenate((t19a,t19b,t19c))

In [21]:
t20a=np.zeros(40)
t20b=np.ones(160)
t20=np.concatenate((t20a,t20b))

In [22]:
t21a=np.zeros(17)
t21b=np.ones(89)
t21c=np.zeros(94)
t21=np.concatenate((t21a,t21b,t21c))

In [23]:
t22a=np.zeros(7)
t22b=np.ones(157)
t22c=np.zeros(36)
t22=np.concatenate((t22a,t22b,t22c))

In [24]:
t23a=np.zeros(41)
t23b=np.ones(130)
t23c=np.zeros(29)
t23=np.concatenate((t23a,t23b,t23c))

In [25]:
t24a=np.zeros(38)
t24b=np.ones(162)
t24=np.concatenate((t24a,t24b))

In [26]:
t25a=np.zeros(9)
t25b=np.ones(112)
t25c=np.zeros(79)
t25=np.concatenate((t25a,t25b,t25c))

In [27]:
t26a=np.zeros(114)
t26b=np.ones(86)
t26=np.concatenate((t26a,t26b))

In [28]:
t27a=np.ones(10)
t27b=np.zeros(36)
t27c=np.ones(66)
t27d=np.zeros(88)
t27=np.concatenate((t27a,t27b,t27c,t27d))

In [29]:
t28a=np.zeros(179)
t28b=np.ones(21)
t28=np.concatenate((t28a,t28b))

In [30]:
t29a=np.ones(150)
t29b=np.zeros(50)
t29=np.concatenate((t29a,t29b))

In [31]:
t30a=np.ones(51)
t30b=np.zeros(13)
t30c=np.ones(49)
t30d=np.zeros(87)
t30=np.concatenate((t30a,t30b,t30c,t30d))

In [32]:
t31a=np.zeros(11)
t31b=np.ones(153)
t31c=np.zeros(36)
t31=np.concatenate((t31a,t31b,t31c))

In [33]:
t32a=np.zeros(18)
t32b=np.ones(97)
t32c=np.zeros(85)
t32=np.concatenate((t32a,t32b,t32c))

In [34]:
t33a=np.zeros(93)
t33b=np.ones(107)
t33=np.concatenate((t33a,t33b))

In [35]:
t34a=np.zeros(16)
t34b=np.ones(184)
t34=np.concatenate((t34a,t34b))

In [36]:
ytraintuple=(t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20,t21)
tmix=np.concatenate(ytraintuple)
ytraininit=np.zeros(6800)
y_train=tmix
#y_train=np.concatenate((ytraininit,tmix))
y_test=np.concatenate((t22,t23,t24,t25,t26,t27,t28,t29,t30,t31,t32,t33,t34))

In [37]:
y_train=y_train.astype('uint8')
y_test=y_test.astype('uint8')

In [38]:
print(y_train.shape)
print(y_test.shape)

(4200,)
(2600,)


In [39]:
print(y_train)
print(y_test)

[0 0 0 ... 0 0 0]
[0 0 0 ... 1 1 1]


In [40]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [42]:
%store y_train
%store y_test

Stored 'y_train' (ndarray)
Stored 'y_test' (ndarray)
